version: 2.1

jobs:
  test:
    docker:
      - image: "node:8"
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm ci --prefix consumer/
      - run: npm ci --prefix publisher/
      - run: npm test --prefix consumer/
      - run: npm test --prefix publisher/

  publish:
    docker:
      - image: "node:8"
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
      - run: npm version --no-git-tag-version $CIRCLE_TAG --prefix consumer/
      - run: npm version --no-git-tag-version $CIRCLE_TAG --prefix publisher/
      - run: cd consumer && npm publish
      - run: cd publisher && npm publish

workflows:
  version: 2
  test:
    jobs:
      - test
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: org-global